### ISSUE TITLE
binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by EnricoSemrau** [umihico/pythonista-chromeless#15]
First of all - Thank you very much for your effort on this! This is awesome.

I did exactly what the readme told me, but when running the function in examples.py I get an error:

Traceback (most recent call last):
  File "/Users/enrico.semrau/PycharmProjects/pythonista-chromeless/pypi/chromeless/chromeless/client_pickler.py", line 19, in _unpickle_result
    return pickle.loads(zlib.decompress(base64.b64decode(base64str_data.encode())))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

When checking the cloudwatch logs there is an error about:
[ERROR] UnboundLocalError: local variable 'screenshothandler' referenced before assignment Traceback (most recent call last):   File "/var/task/lambda_function.py", line 47, in lambda_handler     result = screenshothandler.wrap_with_screenshots(result)
[ERROR] UnboundLocalError: local variable 'screenshothandler' referenced before assignment
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 47, in lambda_handler
    result = screenshothandler.wrap_with_screenshots(result)

------server printing error start------
File "/var/task/lambda_function.py", line 23, in lambda_handler
if event["httpMethod"] == "POST":
KeyError: 'httpMethod'

Can you help me here?

**Comment by umihico** [comment]
Thank you for issuing. I'll check problem.

**Comment by umihico** [comment]
@EnricoSemrau 
I renewed this repository. Could you read new README and try the new deploy way?
I have been thinking this replacement and it was easier for me than fixing previous version. I'm welcome to help if you need to make other issues. I confirmed sls/test.py works

**Comment by EnricoSemrau** [comment]
Thanks for your update. Now it doesnt work at all :(
Which is probably because I still have the old zip file in my lambda and I am not sure how to update it without a new zip.

also for the boto client it is missing the region parameter:
    ssm = boto3.client('ssm')

**Comment by umihico** [comment]
This time users need to use **serverless framework** instead of zip file.
Please run `npm install -g serverless` to install. now you can use `serverless` commands.
The framework create new lambda function and you can ignore previous function.

In my case, this boto3 code works well without the region param, but yes it would be better if I can put boto3 importing in try: block. Thank you 👍

**Comment by EnricoSemrau** [comment]
okay, after adding the region in which the lambda was created:
ssm = boto3.client('ssm', region_name='us-east-1') 
and configure the IAM so serverless has access:
https://serverless.com/framework/docs/providers/aws/guide/credentials/

=> it worked 👍 
Maybe readme should be updated with this.

Thank you so much for your work.

**Comment by umihico** [comment]
Nice! I'm glad to hear that 👍 

Maybe I shouldn't use test.py as example.py. Then I could simplify README and script.
